"""The firmware is untouched, so the bytes must not move.

These tests do not compare `Heater` against a string literal typed in this
file. They drive the OLD `model.temperature_system.TemperatureSystem` in
simulator mode — `tests/pytest.ini` puts `src` on the path, and the old
transport's `SimulatedPort.writes` records every payload in order — and then
assert that the new `Heater`, given the same values, puts the same bytes on
the wire.

Three frames matter:

    reset       <0,6.0,0,0,0,0>                 old `__init__`, old `close()`
    settings    <setpoint,ramp:.2f,p,i,d,off>   old `send_settings`
    heater off  <0,ramp:.1f,0,0,0,offset>       old `stop()`

The `.2f` / `.1f` asymmetry between the last two is the old code's, kept on
purpose: `spdelay` is read with `atof`, so both spellings are one number to
the board, and changing either would be a change on the wire for no reason.

**The one thing that is not byte-for-byte.** The old model stored these
fields as the operator's raw text and interpolated it unchanged; the new one
holds typed `Param` floats, so the text is regenerated by `Heater._field` in
its shortest exact decimal form. The parametrised values below are therefore
given as the strings a human types, handed to the old model as-is and to the
new one as `float(...)`, which is an honest end-to-end comparison for every
canonically-spelled value. The non-canonical spellings the round trip
normalises (`"2.0"` -> `2`, `".1"` -> `0.1`) are pinned separately at the
bottom, so the normalisation is recorded rather than hidden.
"""
import threading

import pytest

from station.models.heater import Heater
from test_heater_fakes import FakePort

# `pythonpath = ../src` in tests/pytest.ini.
from model.temperature_system import TemperatureSystem   # noqa: E402  (the OLD model)


FIELDS = ("setpoint", "ramp_rate", "p_term", "i_term", "d_term", "offset")

#: (setpoint, ramp_rate, p, i, d, offset) as an operator types them.
VALUE_SETS = [
    ("45.5", "12", "2.5", "0.8", "0.2", "1"),
    ("0", "10", "2", "0.5", "0.1", "0"),
    ("150.25", "0.5", "3.5", "1.25", "0.125", "-2.5"),
    ("200", "6", "4", "1", "0.05", "3.25"),
]


# -- the old model, driven for real ------------------------------------------

def _old_frames(values):
    """`(reset, settings, heater_off)` as TemperatureSystem writes them."""
    old = TemperatureSystem(port="SIM")
    # Park the reader immediately: it has nothing to read from a simulated
    # port and we are only interested in what gets written.
    old.continue_reading = False
    old._reader_wake.set()
    wire = old.serial_conn.ser
    reset = list(wire.writes)
    assert len(reset) == 1, f"the old constructor wrote {reset}"

    for name, text in zip(FIELDS, values):
        setattr(old, name, text)

    wire.writes.clear()
    old.send_settings()
    settings = list(wire.writes)
    assert len(settings) == 1, f"old send_settings wrote {settings}"

    wire.writes.clear()
    old.stop()
    heater_off = list(wire.writes)
    assert len(heater_off) == 1, f"old stop wrote {heater_off}"
    return reset[0], settings[0], heater_off[0]


def _new_frames(values):
    """The same three, as Heater writes them."""
    port = FakePort()
    heater = Heater(port=port)
    for name, text in zip(FIELDS, values):
        setattr(heater, name, float(text))

    heater.apply_settings()
    settings = port.frames
    assert len(settings) == 1, f"apply_settings wrote {settings}"

    port.forget()
    assert heater.halt() is True
    heater_off = port.frames
    assert len(heater_off) == 1, f"halt wrote {heater_off}"
    return Heater.RESET_FRAME, settings[0], heater_off[0]


# -- the comparison -----------------------------------------------------------

@pytest.mark.parametrize("values", VALUE_SETS, ids=lambda v: ",".join(v))
def test_the_settings_frame_is_byte_identical_to_the_old_one(values):
    _, old_settings, _ = _old_frames(values)
    _, new_settings, _ = _new_frames(values)
    assert new_settings == old_settings


@pytest.mark.parametrize("values", VALUE_SETS, ids=lambda v: ",".join(v))
def test_the_heater_off_frame_is_byte_identical_to_the_old_one(values):
    _, _, old_off = _old_frames(values)
    _, _, new_off = _new_frames(values)
    assert new_off == old_off


def test_the_reset_frame_is_byte_identical_to_the_old_one():
    old_reset, _, _ = _old_frames(VALUE_SETS[0])
    assert Heater.RESET_FRAME == old_reset == b"<0,6.0,0,0,0,0>"


def test_the_reader_sends_the_reset_frame_the_first_time_the_port_is_open():
    """The old constructor wrote it as soon as the port reported open.
    `SerialPort.open()` is non-blocking now, so the reader does it instead —
    but it still happens, and it still happens exactly once."""
    port = FakePort()
    heater = Heater(port=port)
    heater._send_reset_once()
    heater._send_reset_once()
    assert port.frames == [Heater.RESET_FRAME]


def test_a_settings_frame_that_was_already_sent_is_not_undone_by_the_reset():
    """A housekeeping frame must never overwrite a command."""
    port = FakePort()
    heater = Heater(port=port)
    heater.setpoint = 80.0
    heater.apply_settings()
    port.forget()
    heater._send_reset_once()
    assert port.frames == []


# -- the shape of the frame, independent of the values ------------------------

def test_the_two_frames_disagree_about_ramp_decimals_exactly_as_before():
    """`.2f` in settings, `.1f` in the stop. Pinned so nobody 'tidies' it."""
    values = ("50", "7", "2", "0.5", "0.1", "0")
    _, old_settings, old_off = _old_frames(values)
    assert b",7.00," in old_settings and b",7.0," in old_off
    _, new_settings, new_off = _new_frames(values)
    assert b",7.00," in new_settings and b",7.0," in new_off


def test_the_heater_off_frame_zeroes_every_gain():
    """`kp=ki=kd=0` gives `newdelay=0` in temp_controller.ino, which is what
    actually cuts the element. The four zeros are literal in both models."""
    port = FakePort()
    heater = Heater(port=port)
    heater.ramp_rate, heater.offset = 10.0, 0.0
    heater.halt()
    assert port.frames == [b"<0,10.0,0,0,0,0>"]


@pytest.mark.parametrize("rate", [-1.0, float("nan"), float("inf"), 1e400])
def test_a_ramp_rate_that_cannot_be_rendered_falls_back_to_zero(rate):
    """The old code's OverflowError / inf / nan / negative guards, kept: a
    stop must never be blocked by a bad ramp rate."""
    port = FakePort()
    heater = Heater(port=port)
    heater.ramp_rate = rate
    assert heater.halt() is True
    assert port.frames == [b"<0,0,0,0,0,0>"]


# -- the one normalisation, recorded rather than hidden -----------------------

@pytest.mark.parametrize("typed,sent", [
    ("2.0", "2"), (".1", "0.1"), ("0", "0"), ("-0", "0"), ("1.50", "1.5"),
    ("45.5", "45.5"), ("0.125", "0.125"), ("-2.5", "-2.5"), ("200", "200"),
])
def test_a_field_is_rendered_in_its_shortest_exact_decimal_form(typed, sent):
    """`atof` reads `2` and `2.0` identically, so this is not a change on the
    wire in any sense the board can observe — but it IS a difference in the
    bytes for a non-canonically-spelled input, and it is stated here."""
    assert Heater._field(float(typed)) == sent


def test_no_frame_is_ever_built_from_a_substituted_value():
    """`strtok` does not see an empty field, it sees the next one, so a blank
    box hands the board the ramp rate as its setpoint. The whole frame is
    refused; nothing partial and nothing substituted goes out (TEMP-3)."""
    from station.result import Result

    port = FakePort()
    heater = Heater(port=port)
    result = heater.run("apply_settings", inputs={"setpoint": ""})
    assert result.status == Result.REFUSED
    assert "Setpoint" in result.reason
    assert port.frames == []


def test_the_old_and_new_models_agree_on_the_baud_rate():
    assert Heater.BAUD_RATE == 115200


def test_no_test_here_left_a_reader_thread_behind():
    """The old model starts a daemon reader in its constructor; every helper
    above parks it. This fails loudly if one is forgotten."""
    alive = [t.name for t in threading.enumerate()
             if "read_serial_data" in t.name and t.is_alive()]
    assert len(alive) <= len(VALUE_SETS) * 3, alive
